"use node";

import { v } from 'convex/values'
import { internalAction } from './_generated/server'
import { Supadata } from '@supadata/js'
import OpenAI from 'openai'

export const getYouTubeTranscript = internalAction({
    args: {
        url: v.string(),
    },
    handler: async (ctx, args) => {
        const apiKey = process.env.SUPADATA_API_KEY
        if (!apiKey) {
            throw new Error('SUPADATA_API_KEY not set. Get a free key at https://supadata.ai')
        }

        const supadata = new Supadata({ apiKey })

        console.log("Fetching transcript for:", args.url)

        const result = await supadata.youtube.transcript({
            url: args.url,
            text: true,  // Get plain text instead of segments
            lang: 'en',
        })

        if (!result || !result.content) {
            throw new Error('No transcript available for this video')
        }

        console.log("Transcript length:", result.content.length)
        // console.log("Transcript:", result.content)
        return result.content as string;
    }
})

export const generateSummary = internalAction({
    args: {
        transcript: v.string(),
    },
    handler: async (ctx, args) => {
        console.log("Generating summary")
        const openai = new OpenAI({
            apiKey: process.env.OPENAI_API_KEY,
        })

        const response = await openai.chat.completions.create({
            model: "gpt-4o-mini",
            messages: [
                { role: "system", content: "You are a helpful assistant that needs to summarize the following transcript from a YouTube video. Please provide a few paragraphs that explain the content of the video and also provide a lot of keywords that I could use to improve SEO. Please output in Markdown format." },
                { role: "user", content: `here is my transcript from the youtube video: ${args.transcript}` },
            ],
        })

        if (!response.choices[0].message.content) {
            throw new Error('No summary generated by OpenAI')
        }
        // console.log("Summary:", response.choices[0].message.content)
        return response.choices[0].message.content as string;
    }
})
